### ISSUE TITLE
Replace .length > 0 with !empty?

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-ruby#32]
#### Issue Summary

According to [CodeClimate](https://codeclimate.com/github/sendgrid/smtpapi-ruby/pull/31) we are using .length > 0 in a number of places, please go through and replace them all! 

#### Acceptance
There may be other issues reported by CodeClimate, but there shouldn't be any more .length > 0  issues. The other issues on this report will be added to another issue.

**Comment by valterbarros** [comment]
I think the more idiomatic way is 

`unless @to.empty?`

**Comment by TheJayWright** [comment]
I agree with @valterbarros. `unless @to.empty?` is the dryer method.
