### ISSUE TITLE
Ruby Specific CodeClimate Suggestions 

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-ruby#33]
#### Issue Summary

There are a couple issues reported by CodeClimate:

- Freeze mutable objects assigned to constants. NEW
- Use alias instead of alias_method in a class body.
- Favor a normal if-statement over a modifier clause in a multiline statement. 

Note: `The .length > 0` items reported are covered by another github issue. 

#### Acceptance Criteria
- the issues reported above in this issue are resolved. There may be other issues, they will not block your PR from being merged.

**Comment by valterbarros** [comment]
Guy, do you can list the files with this files messed up?

**Comment by valterbarros** [comment]
I get this issue
