### ISSUE TITLE
Change Content-Transfer-Encoding header

### ISSUE THREAD

**Issue by martijndekuijper** [sendgrid/smtpapi-ruby#4]
Hey guys, when using the SMTP API I'd love to be able to control the Content-Transfer-Encoding header value. Right now I set it in Rails but it's overridden by Sendgrid. Can I do this via the X-SMTPAPI header?

Thanks!

**Comment by jpotts244** [comment]
Would love to take this one on @thinkingserious !

**Comment by kylearoberts** [comment]
@martijndekuijper @jpotts244 

This is not possible currently. When SendGrid touches the email, like when we put tracking into the email it gets converted into quoted-printable. The best option would be to use the green feedback button in your account to let our engineers know this is something you want.
