### ISSUE TITLE
Add CodeCov support to .travis.yml

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-ruby#52]
Issue Summary

Add this to our travis.ci configuration so that code coverage tests will run!

https://github.com/codecov/example-ruby/blob/master/.travis.yml

**Comment by rahulpuroht** [comment]
Hey can you please guide you want to travis.yml file 
rake test ==> bundle exec rake test 
is it correct.?

**Comment by rahulpuroht** [comment]
Hey @mbernier - let me try this one.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/smtpapi-ruby/pull/87
