### ISSUE TITLE
Is this gem a good replacement for stephenb/sendgrid?

### ISSUE THREAD

**Issue by kstevens715** [sendgrid/smtpapi-ruby#88]
#### Issue Summary

I currently have a project that uses [stephenb/sendgrid](https://github.com/stephenb/sendgrid). I'm using it to create the X-SMTPAPI header within a Rails app using ActionMailer/SMTP. The header is being used to define substitutions for all the recipients and the recipient addresses themselves.

[stephenb/sendgrid](https://github.com/stephenb/sendgrid) has not had any new commits in almost 3 years and I was looking to switch to a more official / up to date gem. I saw [sendgrid/sendgrid-ruby](https://github.com/sendgrid/sendgrid-ruby), but I would like to stick with the SMTP API at this time.

I saw this repo and I was wondering if this is a good candidate to replace [stephenb/sendgrid](https://github.com/stephenb/sendgrid)? I see there is a lot of recent activity, but no new gem releases since 2015. Is there a plan to release a new gem update soon?

**Comment by thinkingserious** [comment]
Hello @kstevens715,

I think there will be a release before the end of this year. I'm planning to do a post-Hacktoberfest release for all of our repos once I get back from holiday.
With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
We're now releasing changes about every 2 weeks.
