### ISSUE TITLE
Missing categories for Multipart emails only

### ISSUE THREAD

**Issue by FairyCodeMother** [sendgrid/smtpapi-ruby#89]
#### Issue Summary
As of 6/4 categories have stopped working on our multipart (text and html) emails. There were no deployments that day or the day before that involved emails or email-oriented logic. The only email that still has categories is the text-only email. On 6/28 another category appeared for a few hours on a multipart email, but then stopped again. There was no change in our code. This is my first issue so I'm not sure what all is needed.

If I force a multipart email to be text-only by explicitly setting mail_opts[:content_type] then categories appear for that email. If I do anything to break the multipart of the email, exposing the mimetypes and boundary info in the email, then categories appear for that email. This is unacceptable. 

#### Steps to Reproduce
1. Getting the recipient and from addresses and determine which template to use
2. Set the mail options: subject, recipient, to, any bcc, template path and delivery options (ie: Sendgrid username, password and address: 'smtp.sendgrid.net')
3. Send to SendGrid.mail

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:
* smtpapi-ruby Version: master (latest commit: [commit number])
* Ruby Version: 2.3.3
Our SendGridMailer class inherits from the ApplicationMailer, which inherits from the ActionMailer base class.

Production environment:
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    :address => "smtp.gmail.com",
    :port => 587,
    :authentication => :plain,
    :enable_starttls_auto => true,
    :user_name => "oursuername@domain.com",
    :password => "ourpassword"
  }

**Comment by thinkingserious** [comment]
Hello @FairyCodeMother,

From your example code, it looks like you are using GMail for your SMTP server. If I am mistaken, could you please provide the code that relates to this library so that I may try to reproduce?

Thanks!

With best regards,

Elmer
